export const GET_DONATE_REQUEST = "GET_DONATE_REQUEST";
export const GET_DONATE_SUCCESS = "GET_DONATE_SUCCESS";
export const GET_DONATE_FAIL = "GET_DONATE_FAIL";

export const ADD_DONATE_REQUEST = "ADD_DONATE_REQUEST";
export const ADD_DONATE_SUCCESS = "ADD_DONATE_SUCCESS";
export const ADD_DONATE_FAIL = "ADD_DONATE_FAIL";

export const UPDATE_DONATE_DETAILS_REQUEST = "UPDATE_DONATE_DETAILS_REQUEST";
export const UPDATE_DONATE_DETAILS_SUCCESS = "UPDATE_DONATE_DETAILS_SUCCESS";
export const UPDATE_DONATE_DETAILS_FAIL = "UPDATE_DONATE_DETAILS_FAIL";

export const GET_DONATE_DETAILS_REQUEST = "GET_DONATE_DETAILS_REQUEST";
export const GET_DONATE_DETAILS_SUCCESS = "GET_DONATE_DETAILS_SUCCESS";
export const GET_DONATE_DETAILS_FAIL = "GET_DONATE_DETAILS_FAIL";
export const GET_DONATE_DETAILS_RESET = "GET_DONATE_DETAILS_RESET";